eye = ball : s 0.4 : cr 0 : cb 0 : cg 0 & ball : s 0.35 : tz 0.1 & ball : s 0.15 : cr 0 : cb 0 : cg 0 : tz 0.25

nose = ball : s 0.6 : sy 2 & ball : s 0.3 : tx -0.17 :ty -0.17 :tz 0.2 & ball : s 0.3 : tx 0.17 :ty -0.17 : tz 0.2

moustache = ball : sx 2 : sy 0.2 : sz 0.1 : cb 0 : cr 0 : cg 0

head = ball :s 2.5: cb 0.75 : cg 0.68 :sz 0.1

face = eye : tx -0.5 & eye:tx 0.5 & nose: cb 0.78 : cg 0.75 :ty -0.5 & moustache : ty -0.85 : tz 0.2 & head :tz-0.1 :ty -0.2



$ = face